[tool.black]
exclude= '''
\(
    salt/ext
  | tests/kitchen
  | templates
)/


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip=salt/ext,tests/kitchen,templates
