blank_issues_enabled: true
contact_links:
  - name: Salt Community Discord
    url: https://discord.com/invite/J7b7EscrAs
    about: Please ask and answer questions here.
  - name: Salt-Users Forum
    url: https://groups.google.com/forum/#!forum/salt-users
    about: Please ask and answer questions here.
  - name: Salt on LiberaChat
    url: https://web.libera.chat/#salt
    about: Please ask and answer questions here.
