name: Build Salt Packages

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: On which GitHub Environment Context To Run
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
      nightly-build:
        type: boolean
        default: false
      rc-build:
        type: boolean
        default: false
    secrets:
      SECRETS_KEY:
        required: true

env:
  COLUMNS: 160

jobs:
  build-deb:
    name: Build DEB Repositories
    uses: ./.github/workflows/build-deb-repo.yml
    with:
      environment: ${{ inputs.environment }}
      salt-version: "${{ inputs.salt-version }}"
      nightly-build: ${{ inputs.nightly-build }}
      rc-build: ${{ inputs.rc-build }}
    secrets:
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}

  build-rpm:
    name: Build RPM Repositories
    uses: ./.github/workflows/build-rpm-repo.yml
    with:
      environment: ${{ inputs.environment }}
      salt-version: "${{ inputs.salt-version }}"
      nightly-build: ${{ inputs.nightly-build }}
      rc-build: ${{ inputs.rc-build }}
    secrets:
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}

  build-windows:
    name: Build Windows Repositories
    uses: ./.github/workflows/build-windows-repo.yml
    with:
      environment: ${{ inputs.environment }}
      salt-version: "${{ inputs.salt-version }}"
      nightly-build: ${{ inputs.nightly-build }}
      rc-build: ${{ inputs.rc-build }}
    secrets:
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}

  build-macos:
    name: Build macOS Repositories
    uses: ./.github/workflows/build-macos-repo.yml
    with:
      environment: ${{ inputs.environment }}
      salt-version: "${{ inputs.salt-version }}"
      nightly-build: ${{ inputs.nightly-build }}
      rc-build: ${{ inputs.rc-build }}
    secrets:
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
