---
name: Build RPM Packages

on:
  workflow_call:
    inputs:
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.

env:
  COLUMNS: 190

jobs:
  build:
    name: RPM
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        src:
          - true
          - false

    container:
      image: ghcr.io/saltstack/salt-ci-containers/packaging:centosstream-9

    steps:
      - uses: actions/checkout@v3

      - name: Download Onedir Tarball as an Artifact
        uses: actions/download-artifact@v3
        with:
          name: salt-${{ inputs.salt-version }}-onedir-linux-${{ matrix.arch }}.tar.xz
          path: artifacts/

      - name: Download Release Patch
        if: ${{ startsWith(github.event.ref, 'refs/tags') == false }}
        uses: actions/download-artifact@v3
        with:
          name: salt-${{ inputs.salt-version }}.patch

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Setup Salt Version
        id: setup-salt-version
        uses: ./.github/actions/setup-salt-version
        with:
          salt-version: "${{ inputs.salt-version }}"

      - name: Configure Git
        if: ${{ startsWith(github.event.ref, 'refs/tags') == false }}
        run: |
          tools pkg configure-git

      - name: Apply release patch
        if: ${{ startsWith(github.event.ref, 'refs/tags') == false }}
        run: |
          tools pkg apply-release-patch salt-${{ inputs.salt-version }}.patch --delete

      - name: Build RPM
        if: ${{ matrix.src != true}}
        run: |
          tools pkg build rpm --onedir salt-${{ inputs.salt-version }}-onedir-linux-${{ matrix.arch }}.tar.xz

      - name: Build RPM
        if: ${{ matrix.src == true}}
        run: |
          tools pkg build rpm

      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        if: ${{ matrix.src != true}}
        with:
          name: salt-${{ inputs.salt-version }}-${{ matrix.arch }}-rpm
          path: ~/rpmbuild/RPMS/${{ matrix.arch }}/*.rpm
          retention-days: 7
          if-no-files-found: error

      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        if: ${{ matrix.src == true}}
        with:
          name: salt-${{ inputs.salt-version }}-${{ matrix.arch }}-rpm-from-src
          path: ~/rpmbuild/RPMS/${{ matrix.arch }}/*.rpm
          retention-days: 7
          if-no-files-found: error
