name: Lint

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files

jobs:
  Salt:
    name: Lint Salt's Source Code
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || fromJSON(inputs.changed-files)['salt'] || fromJSON(inputs.changed-files)['lint'] }}

    container:
      image: python:3.8-slim-buster

    steps:
      - name: Install System Deps
        run: |
          echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
          apt-get update
          apt-get install -y enchant git gcc make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev
          apt-get install -y git/buster-backports

      - uses: actions/checkout@v3

      - name: Install Nox
        env:
          PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Install Python Requirements
        env:
          PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
        run:
          nox --install-only --forcecolor -e lint-salt

      - name: Lint Changed Files
        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['salt'] && ! fromJSON(inputs.changed-files)['lint']
        env:
          SKIP_REQUIREMENTS_INSTALL: YES
        run: |
          nox --forcecolor -e lint-salt -- ${{ join(fromJSON(inputs.changed-files)['salt_files'], ' ') }}

      - name: Lint ALL Files
        if: github.event_name != 'pull_request' || fromJSON(inputs.changed-files)['lint']
        env:
          SKIP_REQUIREMENTS_INSTALL: YES
        run: |
          nox --forcecolor -e lint-salt

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-lint-salt

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error

  Tests:
    name: Lint Salt's Test Suite
    runs-on: ubuntu-latest
    if: ${{ fromJSON(inputs.changed-files)['tests'] || fromJSON(inputs.changed-files)['lint'] }}

    container:
      image: python:3.8-slim-buster

    steps:
      - name: Install System Deps
        run: |
          echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
          apt-get update
          apt-get install -y enchant git gcc make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev
          apt-get install -y git/buster-backports

      - uses: actions/checkout@v3

      - name: Install Nox
        env:
          PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Install Python Requirements
        env:
          PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
        run:
          nox --install-only --forcecolor -e lint-tests

      - name: Lint Changed Files
        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['tests'] && ! fromJSON(inputs.changed-files)['lint']
        env:
          SKIP_REQUIREMENTS_INSTALL: YES
        run: |
          nox --forcecolor -e lint-tests -- ${{ join(fromJSON(inputs.changed-files)['tests_files'], ' ') }}

      - name: Lint ALL Files
        if: github.event_name != 'pull_request' || fromJSON(inputs.changed-files)['lint']
        env:
          SKIP_REQUIREMENTS_INSTALL: YES
        run: |
          nox --forcecolor -e lint-tests

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-lint-salt

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
