name: Twine Check

on: [push, pull_request]

jobs:
  Twine-Check:
    name: Run 'twine check' Against Salt

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('README.rst') }}-${{ hashFiles('.github/workflows/twine-check.yml') }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install twine>=3.4.1
    - name: Python setup
      run: |
        python3 setup.py sdist
    - name: Twine check
      run: |
        python3 -m twine check dist/*
